### ISSUE TITLE
generated data file is too big

### ISSUE THREAD

**Issue by chylli-binary** [DrHyde/perl-modules-Number-Phone#109]
share/dist/Number-Phone/Number-Phone-UK-Data.db is 100.53 MB. Can it be compressed ? I cannot add it into git repo.
```

remote: error: File local/lib/perl5/auto/share/dist/Number-Phone/Number-Phone-UK-Data.db is 100.52 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

```

**Comment by DrHyde** [comment]
If you don't need the extra features that that file enables - mostly info on which telcos have been assigned which numbers - then you can use the `--without_uk` option to Makefile.PL when installing. See instructions in the README.

In the long term I plan to switch to using `Data::CompactReadonly` instead of `DBM::Deep` for that database. However, that requires a deprecation period as it will also mean that the module will no longer work on 32 bit perls. The earliest that will happen is June 2023.

**Comment by chylli-binary** [comment]
Really thank you for your reply. Can I remove that big file after I install it with normal `cpanm` command ?  installing it with `--without_ok` will increase complexity in my case.

**Comment by DrHyde** [comment]
Yes, I think that should be sufficient.

**Comment by DrHyde** [comment]
FYI the next release uses a different file format for the UK database. The file will be about 6% of the size of the previous format.
